const images = {
  background: require('../assets/images/background.png'),
  logo: require('../assets/images/mixtape-logo.png'),
  facebookButton: require('../assets/images/facebook-button.png'),
  phoneButton: require('../assets/images/phone-button.png'),
  spotifyButton: require('../assets/images/spotify-button.png'),
  home: require('../assets/images/home.png'),
  friends: require('../assets/images/friends.png'),
  shop: require('../assets/images/shop.png'),
  settings: require('../assets/images/settings.png'),
  cardRibbon: require('../assets/images/card-ribbon.png'),
  mixtape: require('../assets/images/mixtape.jpg'),
  avatarPlaceholder: require('../assets/images/avatar-placeholder.png'),
  currency: require('../assets/images/currency.png'),
  invite: require('../assets/images/invite.png'),
  purchaseButton: require('../assets/images/purchase-button.png'),
  breakingGamesLogo: require('../assets/images/breaking-games-logo.jpg'),
  mixtapeBox: require('../assets/images/mixtape-box.jpg'),
  coinsGold: require('../assets/images/coins-gold.png'),
  globe: require('../assets/images/globe.png'),
  stopwatch: require('../assets/images/stopwatch.png'),
  crownedTape: require('../assets/images/crowned-tape.png'),
  tape: require('../assets/images/tape.png'),
  quitGameButton: require('../assets/images/quit-game-button.png'),
  submitButton: require('../assets/images/submit-button.png'),
  songBarPlay: require('../assets/images/song-bar-play.png'),
  songBarPause: require('../assets/images/song-bar-pause.png'),
  addToPlaylist: require('../assets/images/add-to-playlist.png'),
  highlightedSongBar: require('../assets/images/highlighted-song-bar.png'),
  check: require('../assets/images/check.png'),
  search: require('../assets/images/search.png'),
  playFriends: require('../assets/images/playFriends.png'),
  playOthers: require('../assets/images/playOthers.png'),
  gamePlay: require('../assets/images/gamePlay.png'),
  lobbyHostFriends: require('../assets/images/lobbyHostFriends.png'),
  facebookFriends: require('../assets/images/facebookFriends.png'),
  contactFriends: require('../assets/images/contactFriends.png'),
  lobbyOthers: require('../assets/images/lobbyOthers.png'),
  x: require('../assets/images/x.png'),
  equalizer: require('../assets/images/equalizer.gif')
};

export default images;
