const localization = {
  chooseLogin: 'LOGIN USING YOUR PREMIUM\nSPOTIFY ACCOUNT!',
  connectToSpotify: 'CONNECT MIXTAPE TO\nYOUR SPOTIFY ACCOUNT:',
  requireSpotifyPremium: 'REQUIRES SPOTIFY PREMIUM',
  playWithFriends: 'Play with\nfriends?',
  playWithOthers: 'Play with\nothers?',
  free: 'FREE',
  oneDollar: '1 X $',
  twentyGameCredits: '20 GAME CREDITS',
  loadingGame: 'LOADING GAME',
  playersInQueue: (current, max) =>
    `${current} OF ${max} PLAYERS IN THE CUE...`,
  waitingForOthers: 'WAITING FOR OTHERS...',
  playersHave60Seconds: 'PLAYERS HAVE 60 SECONDS TO PICK AND PLAY A SONG.',
  gameWinnerReceives: 'GAME WINNER RECEIVES\n2 ',
  rewards: ' REWARDS!',
  round1: 'ROUND ONE',
  round2: 'ROUND TWO',
  round3: 'ROUND THREE',
  round4: 'ROUND FOUR',
  round5: 'ROUND FIVE',
  searchSpotify: 'SEARCH SPOTIFY',
  chooseWinner: 'CHOOSE THE WINNER',
  winner: 'WINNER',
  congratulations: 'CONGRATULATIONS!',
  overallWinner: 'OVERALL WINNER',
  quitGame: 'QUIT GAME',
  profile: 'PROFILE',
  logout: 'LOGOUT',
  username: 'USERNAME',
  email: 'EMAIL ADDRESS',
  search: 'Search',
  sendInvites: (num = 0) => `SEND INVITES (${num})`,
  tieBreaker: 'TIE BREAKER',
  letsGo: "LET'S GO",
  wantToPlayWithYou: 'WANTS TO PLAY MIXTAPE WITH YOU!',
  help: 'HELP',
  enableFacebook: 'Enable Facebook',
  enableContacts: 'Enable Contacts',
  pleaseSelectSong: 'Please select a song',
  okay: 'Okay',
  areYouSureToAddSong: 'Are you sure you want to add this song on this card?',
  yes: 'Yes',
  no: 'No'
};

export default localization;
